development:
  options:
    raise_not_found_error: false
  clients:
    default:
      database: web_crawler_api_development
      hosts:
        - localhost:27017
      options:
        server_selection_timeout: 1